# Секреты Темнолесья

- Автор: Наталья Пронько
- Дата: 05.06.2026

### Цели и задачи проекта

В данном проекте мы используем датасет new_games.csv, который содержит информацию о продажах игр разных жанров и платформ, а также пользовательские и экспертные оценки игр. На примере датасета познакомимся с данными, проверим их корректность и проведем предобработку, получив необходимый срез данных.

       
Перед анализом сделаем следующее:

* Отберем данные по времени выхода игры. Нам нужен период с 2000 по 2013 год включительно.
* Категоризируем игры по оценкам пользователей и экспертов. Выделим три категории:
     - высокая оценка — с оценкой от 8 до 10 и от 80 до 100, включая правые границы интервалов.
     - средняя оценка — с оценкой от 3 до 8 и от 30 до 80, не включая правые границы интервалов.
     - низкая оценка — с оценкой от 0 до 3 и от 0 до 30, не включая правые границы интервалов.
* Выделим топ-7 платформ по количеству игр, выпущенных за весь требуемый период.

### Описание данных

    В проекте будут использованы данные датасета hotel_dataset.csv,содержащие информацию о продажах игр разных       жанров и платформ, а также пользовательские и экспертные оценки игр:
    
- `Name` — название игры.
- `Platform` — название платформы.
- `Year of Release` — год выпуска игры.
- `Genre` — жанр игры.
- `NA sales` — продажи в Северной Америке (в миллионах проданных копий).
- `EU sales` — продажи в Европе (в миллионах проданных копий).
- `JP sales` — продажи в Японии (в миллионах проданных копий).
- `Other sales` — продажи в других странах (в миллионах проданных копий).
- `Critic Score` — оценка критиков (от 0 до 100).
- `User Score` — оценка пользователей (от 0 до 10).
- `Rating` — рейтинг организации ESRB (англ. Entertainment Software Rating Board). Эта ассоциация определяет рейтинг компьютерных игр и присваивает им подходящую возрастную категорию.

### Содержимое проекта


 1. Загрузка и знакомство с данными
 2. Проверка ошибок в данных и их предобработка. Что нужно проверить:
    - Названия, или метки, столбцов датафрейма
    - Типы данных
    - Наличие пропусков в данных
    - Явные и неявные дубликаты в данных
 3. Фильтрация данных
 4. Категоризация данных

##  Загрузка данных и знакомство с ними

Загрузим необходимые библиотеки для анализа данных и данные из датасета new_games.csv. Затем выведем основную информацию о данных с помощью метода info() и первые и последние строки датафрейма.

In [78]:
# Импортируем библиотеку pandas
import pandas as pd

import warnings
warnings.filterwarnings('ignore')

In [6]:
# Выгружаем данные из датасета `/datasets/new_games.csv`  в датафрейм games
games = pd.read_csv('new_games.csv')

In [7]:
# Выводим информацию о датафрейме
games.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16956 entries, 0 to 16955
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Name             16954 non-null  object
 1   Platform         16956 non-null  object
 2   Year of Release  16681 non-null  float64
 3   Genre            16954 non-null  object
 4   NA sales         16956 non-null  float64
 5   EU sales         16956 non-null  object
 6   JP sales         16956 non-null  object
 7   Other sales      16956 non-null  float64
 8   Critic Score     8242 non-null   float64
 9   User Score       10152 non-null  object
 10  Rating           10085 non-null  object
dtypes: float64(4), object(7)
memory usage: 1.4+ MB

In [8]:
# Выводим первые строки датафрейма на экран
games.head()

,Name,Platform,Year of Release,Genre,NA sales,EU sales,JP sales,Other sales,Critic Score,User Score,Rating
0,Wii Sports,Wii,2006.0,Sports,41.36,28.96,3.77,8.45,76.0,8,E
1,Super Mario Bros.,NES,1985.0,Platform,29.08,3.58,6.81,0.77,NaN,NaN,NaN
2,Mario Kart Wii,Wii,2008.0,Racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,Wii Sports Resort,Wii,2009.0,Sports,15.61,10.93,3.28,2.95,80.0,8,E
4,Pokemon Red/Pokemon Blue,GB,1996.0,Role-Playing,11.27,8.89,10.22,1.00,NaN,NaN,NaN

In [9]:
# Выводим последние строки датафрейма на экран
games.tail()

,Name,Platform,Year of Release,Genre,NA sales,EU sales,JP sales,Other sales,Critic Score,User Score,Rating
16951,Samurai Warriors: Sanada Maru,PS3,2016.0,Action,0.00,0.0,0.01,0.0,NaN,NaN,NaN
16952,LMA Manager 2007,X360,2006.0,Sports,0.00,0.01,0.0,0.0,NaN,NaN,NaN
16953,Haitaka no Psychedelica,PSV,2016.0,Adventure,0.00,0.0,0.01,0.0,NaN,NaN,NaN
16954,Spirits & Spells,GBA,2003.0,Platform,0.01,0.0,0.0,0.0,NaN,NaN,NaN
16955,Winning Post 8 2016,PSV,2016.0,Simulation,0.00,0.0,0.01,0.0,NaN,NaN,NaN

Датасет new_games.csv содержит 11 столбцов и 16956 строк, в которых содержится информация о продажах игр разных жанров и платформ, а также пользовательские и экспертные оценки игр.
    
Изучим типы данных и их корректность:

* **Числовые значения с плавающей точкой (float64)**. Четыре столбца представлены типом float64: Year of Release, NA sales, Other sales, Critic Score. В столбцах Year of Release и Critic Score тип данных необходимо поменять на int64 и уменьшить разрядность, так как в Year of Release это четырехзначное число, а Critic Score двухзначное. Для NA sales и Other sales этот тип корректен, так как продажи представлены дробными числами.

* **Строковые данные (object)**.  7 столбцов представлены типом object. Столбцы Name, Platform, Genre, Rating содержат текстовые данные (название игры, название платформы, жанр игры, рейтинг ESRB) и для них тип данных object подходит. Для столбцов EU sales, JP sales и User Score тип данных object не подходит, так как там содержатся числовые данные. Так как продажи и оценка пользователей в этих столбцах содержат дробные значения, будет корректно поменять тип данных на float64.


После анализа данных выявлено, что некоторые столбцы нуждаются в смене типа данных. Далее будет проведен детальный анализ и корректировка по типам данных,  названиям столбцов, пропускам и дубликатам.

## Проверка ошибок в данных и их предобработка


### Названия, или метки, столбцов датафрейма

В этом разделе проверим названия всех столбцов и проверим их стиль написания

In [10]:
games.columns

Index(['Name', 'Platform', 'Year of Release', 'Genre', 'NA sales', 'EU sales',
       'JP sales', 'Other sales', 'Critic Score', 'User Score', 'Rating'],
      dtype='object')

Для дальнейшей работы нам удобнее привести все названия столбцов к нижнему регистру и заменить все пробелы на подчеркивания (стиль snake case).

In [11]:
# Сохраняем в список желаемые названия столбцов
columns_snake_case = ['name', 'platform', 'year_of_release', 'genre', 'na_sales', 'eu_sales',
       'jp_sales', 'other_sales', 'critic_score', 'user_score', 'rating']

In [12]:
# Передаем список атрибуту columns датафрейма
games.columns = columns_snake_case

In [13]:
# Убедимся, что названия приведены к стилю snake case
games.columns

Index(['name', 'platform', 'year_of_release', 'genre', 'na_sales', 'eu_sales',
       'jp_sales', 'other_sales', 'critic_score', 'user_score', 'rating'],
      dtype='object')

### Типы данных

* В столбце year_of_release тип float64 вместо int64 по причине того, что в столбце встречаются пропуски. В столбцах с числовым типом данных пропуски, при выгрузке данных в датафрейм, обозначаются как NaN и имеют тип float64.
* В столбцах eu_sales, jp_sales, user_score тип данных object по причине того, что встречаются строковые значения, например unknown, tbd.

In [14]:
games.dtypes

name                object
platform            object
year_of_release    float64
genre               object
na_sales           float64
eu_sales            object
jp_sales            object
other_sales        float64
critic_score       float64
user_score          object
rating              object
dtype: object

Так как доля пропусков в столбце year_of_release составляет 1,6% лучшим решением для дальнейшей работы по анализу будет удалить строки с пропусками и, как говорили ранее, приведем столбец к типу данных int64 и уменьшим разрядность

In [17]:
# Удалим строки с пропусками в столбце year_of_release
games = games.dropna(subset=['year_of_release'])

In [18]:
# Приведем столбец к типу данных int64  и уменьшим разрядность
games['year_of_release'] = pd.to_numeric(games['year_of_release'], downcast='integer')

In [19]:
# Проверим результат
games['year_of_release'].dtypes

dtype('int16')

In [20]:
# Подсчитаем сколько осталось строк после удаления
games.shape[0]

16681

Приведем числовые столбцы со строковыми значениями к числовому типу данных, заменив строковые значения на пропуски.

In [21]:
# Приведем числовой столбец eu_sales со строкового типа данных к float64
# строковые значения заменим на NaN c помощью парметра errors и его аргумента coerce
games['eu_sales'] = pd.to_numeric(games['eu_sales'], errors='coerce')

In [22]:
# Приведем числовой столбец jp_sales со строкового типа данных к float64
# строковые значения заменим на NaN c помощью парметра errors и его аргумента coerce
games['jp_sales'] = pd.to_numeric(games['jp_sales'], errors='coerce')

В столбце user_score также встречаются строковые значения (напр. tbd), проведем преобразования и с ним

In [23]:
games['user_score'] = pd.to_numeric(games['user_score'], errors='coerce')

Проверим результат

In [24]:
games.dtypes

name                object
platform            object
year_of_release      int16
genre               object
na_sales           float64
eu_sales           float64
jp_sales           float64
other_sales        float64
critic_score       float64
user_score         float64
rating              object
dtype: object

Преобразобания прошли успешно

### Наличие пропусков в данных

Посчитаем количество пропусков в каждом столбце в абсолютных и относительных значениях.

In [25]:
# Посчитаем количество пропусков в абсолютном значении в каждом столбце
games.isna().sum().sort_values(ascending=False)

user_score         9123
critic_score       8596
rating             6780
eu_sales              6
jp_sales              4
name                  2
genre                 2
platform              0
year_of_release       0
na_sales              0
other_sales           0
dtype: int64

In [26]:
# Посчитаем количество пропусков в относительном значении в каждом столбце
games.isna().mean().sort_values(ascending=False)

user_score         0.546910
critic_score       0.515317
rating             0.406450
eu_sales           0.000360
jp_sales           0.000240
name               0.000120
genre              0.000120
platform           0.000000
year_of_release    0.000000
na_sales           0.000000
other_sales        0.000000
dtype: float64

Промежуточный вывод по пропускам

В ходе анализа выявлено, что значительная часть пропусков (от 40% до 55%) сосредоточена в столбцах с оценками (user_score, critic_score) и рейтингом ESRB (rating). Это объясняется тем, что систематический сбор пользовательских и экспертных оценок начался относительно недавно, и для многих старых игр (особенно выпущенных до середины 2000-х) эти данные отсутствуют. Кроме того, оценки присваивались преимущественно популярным играм, тогда как малоизвестные проекты часто оставались без рейтинга.

Пропуски в столбцах eu_sales, jp_sales, name, genre носят единичный характер (менее 0.04%) и, вероятно, связаны с техническими ошибками при вводе данных.

Приступаем к обработке пропущенных значений.

Так как мы заменили строковые значения в столбцах eu_sales и jp_sales на NaN, то теперь заменим эти пропуски на среднее значение по региону:

In [27]:
# Считаем среднее значение по столбцу eu_sales
mean_eu = games['eu_sales'] .mean()

In [28]:
# Заполняем столбец eu_sales средними значениями 
games['eu_sales'] = games['eu_sales'].fillna(mean_eu)

In [29]:
# Убедимся, что в столбце eu_sales нет пропусков
games['eu_sales'].isna().mean()

0.0

In [30]:
# Считаем среднее значение по столбцу jp_sales
mean_jp = games['jp_sales'] .mean()

In [31]:
# Заполняем столбец jp_sales средними значениями 
games['jp_sales'] = games['jp_sales'].fillna(mean_eu)

In [32]:
# Убедимся, что в столбце jp_sales нет пропусков
games['jp_sales'].isna().mean()

0.0

Так как доля пропусков в столбцах user_score и critic_score довольно высокая (55% и 52% соответственно), корректно будет заполнить пропуски в данных столбцах индикаторами. Примем за индикатор значение -1.

In [33]:
# Заполняем пропуски в столбце critic_score индикатором -1
games['critic_score'] = games['critic_score'].fillna(-1)

In [34]:
# Убедимся, что в столбце critic_score нет пропусков
games['critic_score'].isna().mean()

0.0

In [35]:
# Заполняем пропуски в столбце user_score индикатором -1
games['user_score'] = games['user_score'].fillna(-1)

In [36]:
# Убедимся, что в столбце user_score нет пропусков
games['user_score'].isna().mean()

0.0

### Явные и неявные дубликаты в данных

Проверим уникальные значения в столбцах с названиями жанра игры, платформы, рейтинга и года выпуска:

In [37]:
# Для подсчета уникальных значений воспользуемся методом nunique()
unique_combinations_count = games[['name','genre', 'platform', 'rating', 'year_of_release' ]].nunique()

In [38]:
unique_combinations_count

name               11426
genre                 24
platform              31
rating                 8
year_of_release       37
dtype: int64

Проверим встречаются ли неявные дубликаты, связанные с опечатками или разным способом написания в столбце genre:

In [39]:
# Для подсчёта количества вхождений каждого уникального значения в столбце подходит метод value_counts()
games['genre'].value_counts()

genre
Action          3341
Sports          2325
Misc            1740
Role-Playing    1493
Shooter         1314
Adventure       1309
Racing          1244
Platform         891
Simulation       866
Fighting         844
Strategy         679
Puzzle           577
ACTION            12
SPORTS             7
ROLE-PLAYING       6
RACING             6
FIGHTING           6
SHOOTER            5
ADVENTURE          4
MISC               3
PLATFORM           3
PUZZLE             2
SIMULATION         1
STRATEGY           1
Name: count, dtype: int64

Как видим в столбце присутствую неявные дубликаты(напр. Action - ACTION,Sports - SPORTS, Role-Playing - ROLE-PLAYING и др.) нормализуем столбец, приведем все данные в столбце к нижнему регистру

In [40]:
# Прибегнем к помощи акцессора str и метода lower()
games['genre'] = games['genre'].str.lower()

In [41]:
# Проверим результат
games['genre'].value_counts()

genre
action          3353
sports          2332
misc            1743
role-playing    1499
shooter         1319
adventure       1313
racing          1250
platform         894
simulation       867
fighting         850
strategy         680
puzzle           579
Name: count, dtype: int64

Проверим встречаются ли неявные дубликаты, связанные с опечатками или разным способом написания в столбце platform:

In [42]:
games['platform'].value_counts()

platform
PS2     2154
DS      2147
PS3     1330
Wii     1305
X360    1249
PSP     1212
PS      1208
PC       972
GBA      826
XB       818
GC       549
3DS      522
PSV      434
PS4      395
N64      320
XOne     251
SNES     241
SAT      174
WiiU     147
2600     118
NES      100
GB        97
DC        52
GEN       29
NG        12
SCD        6
WS         6
3DO        3
TG16       2
GG         1
PCFX       1
Name: count, dtype: int64

В столбце platform нет дублирования

Проверим столбец rating

In [43]:
games['rating'].value_counts()

rating
E       3968
T       2948
M       1558
E10+    1414
EC         8
K-A        3
AO         1
RP         1
Name: count, dtype: int64

Всего в рейтинге ESRB 7 категорий, в нашем столбце обнаружилось 8. Категория K-A это устаревшее обозначение категории E. Заменим это обозначение.

In [44]:
# Нам поможет str с методом replace()
games['rating'] = games['rating'].str.replace('K-A', 'E')

In [45]:
games['rating'].value_counts()

rating
E       3971
T       2948
M       1558
E10+    1414
EC         8
AO         1
RP         1
Name: count, dtype: int64

Теперь в рейтинге ESRB 7 категорий, как и положено

Проверим столбец year_of_release:

In [49]:
games['year_of_release'].value_counts().sort_index()

year_of_release
1980       9
1981      46
1982      37
1983      18
1984      14
1985      14
1986      22
1987      17
1988      15
1989      17
1990      16
1991      42
1992      43
1993      62
1994     121
1995     220
1996     267
1997     293
1998     384
1999     341
2000     357
2001     491
2002     839
2003     789
2004     771
2005     950
2006    1020
2007    1218
2008    1445
2009    1450
2010    1279
2011    1149
2012     670
2013     552
2014     584
2015     612
2016     507
Name: count, dtype: int64

В столбце данные начинаются с 1980 года и по 2016гг. В плане дубликатов в столбце все в порядке.

Так как в столбце name много вхождений (11426), сразу приведем все данные к нижнему регистру:

In [47]:
games['name'] = games['name'].str.lower()

In [48]:
games['name'].nunique()

11426

Ни на что не повлияло

Теперь проверим наличие явных дубликатов в данных

In [51]:
games.info()

<class 'pandas.core.frame.DataFrame'>
Index: 16681 entries, 0 to 16955
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   name             16679 non-null  object
 1   platform         16681 non-null  object
 2   year_of_release  16681 non-null  int16
 3   genre            16679 non-null  object
 4   na_sales         16681 non-null  float64
 5   eu_sales         16681 non-null  float64
 6   jp_sales         16681 non-null  float64
 7   other_sales      16681 non-null  float64
 8   critic_score     16681 non-null  float64
 9   user_score       16681 non-null  float64
 10  rating           9901 non-null   object
dtypes: float64(6), int16(1), object(4)
memory usage: 1.4+ MB

In [52]:
# Используем методы duplicated()и sum() для подсчета дубликатов
full_duplicate = games.duplicated().sum()

In [53]:
full_duplicate

235

Используя методы sort_values() и duplicated() посмотрим на дубликаты:

In [54]:
games_sorted = games.sort_values(by=games.columns.tolist())

In [55]:
duplicates = games_sorted[games_sorted.duplicated(keep=False)]

In [56]:
duplicates

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
15191,beyblade burst,3DS,2016,role-playing,0.00,0.00,0.03,0.00,-1.0,-1.0,NaN
15192,beyblade burst,3DS,2016,role-playing,0.00,0.00,0.03,0.00,-1.0,-1.0,NaN
15301,11eyes: crossover,X360,2009,adventure,0.00,0.00,0.02,0.00,-1.0,-1.0,NaN
15302,11eyes: crossover,X360,2009,adventure,0.00,0.00,0.02,0.00,-1.0,-1.0,NaN
4860,18 wheeler: american pro trucker,PS2,2001,racing,0.20,0.15,0.00,0.05,61.0,5.7,E
...,...,...,...,...,...,...,...,...,...,...,...
2909,yu-gi-oh! the falsebound kingdom,GC,2002,strategy,0.49,0.13,0.07,0.02,-1.0,-1.0,NaN
6695,zoo resort 3d,3DS,2011,simulation,0.11,0.09,0.03,0.02,-1.0,-1.0,E
6696,zoo resort 3d,3DS,2011,simulation,0.11,0.09,0.03,0.02,-1.0,-1.0,E
8156,zumba fitness rush,X360,2012,sports,0.00,0.16,0.00,0.02,73.0,6.2,E10+
8157,zumba fitness rush,X360,2012,sports,0.00,0.16,0.00,0.02,73.0,6.2,E10+

In [57]:
# Посчитаем строки с дубликатами
games_with_duplicates = games.shape[0]

In [58]:
games_with_duplicates

16681

In [59]:
# Удалим дубликаты с помощью метода drop_duplicates()
games = games.drop_duplicates()

In [60]:
# Посчитаем строки без дубликатов
games.shape[0]

16446

удалили 235 дубликатов

**Промежуточный вывод по дубликатам**

В ходе анализа выявлено и обработано **235 явных дубликатов** (полностью идентичных строк), что составляет около 1.4% от общего объёма данных. Дубликаты удалены с помощью метода `drop_duplicates()`.

**Неявные дубликаты:**
- **В столбце `genre`:** обнаружены различия в регистре (`Action`/`ACTION`, `Sports`/`SPORTS` и др.). Все значения приведены к нижнему регистру, количество уникальных жанров сократилось с 24 до 12.
- **В столбце `rating`:** выявлено устаревшее обозначение `K-A` (3 записи), которое заменено на современное `E` (Everyone). Теперь столбец содержит 7 стандартных категорий ESRB.
- **В столбцах `platform`, `year_of_release`, `name`:** неявных дубликатов не обнаружено. Для единообразия названия игр приведены к нижнему регистру.

**Результат:** После обработки дубликатов и нормализации данных объём датафрейма составляет 16 446 строк без дубликатов, все категориальные столбцы приведены к единому формату.

**Количество удалённых строк**

**Исходные данные:** 16 956 строк

| Операция | Удалено строк | Доля от исходных |
|----------|--------------|------------------|
| Удаление пропусков в `year_of_release` | 275 | 1.62% |
| Удаление дубликатов | 235 | 1.39% |
| **Всего** | **510** | **3.01%** |

**Результат:** Финальный объём данных — **16 446 строк** (сохранено 96.99% исходных данных). Удаление 3% данных является допустимым и не влияет на репрезентативность выборки.

**Общий промежуточный вывод**

В ходе предобработки данных выполнены следующие действия:

**1. Исправление типов данных:**
- `year_of_release` приведён к int64 (после удаления пропусков)
- `eu_sales`, `jp_sales`, `user_score` преобразованы в float64
- Причина некорректных типов: пропуски, строковые значения

**2. Обработка пропусков:**
- `user_score` (55%) и `critic_score` (52%) — заполнены индикатором -1

**3. Обработка дубликатов:**
- Удалено 235 явных дубликатов (1.39%)
- Устранены неявные дубликаты в `genre` (приведение к нижнему регистру)
- Заменено устаревшее обозначение `K-A` на `E` в столбце `rating`


**4. Итоговая статистика:**
- Исходный объём: 16 956 строк
- Удалено всего: 510 строк (3.01%)
- Финальный объём: 16 446 строк (сохранено 96.99% данных)

**Вывод:** Данные успешно очищены, нормализованы и подготовлены к анализу. Потеря 3% данных является незначительной и не влияет на репрезентативность выборки для исследования игровой индустрии 2000-2013 годов.

## Фильтрация данных

Коллеги хотят изучить историю продаж игр в начале XXI века, и их интересует период с 2000 по 2013 год включительно. Отберем данные по этому показателю. Сохраним новый срез данных в отдельном датафрейме `df_actual`.

In [61]:
# Для фильтрации воспользуемся атрибутом loc
df_actual = games.loc[(games['year_of_release'] >= 2000) & (games['year_of_release'] <= 2013) ]

In [62]:
# Проверим результат
df_actual

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating
0,wii sports,Wii,2006,sports,41.36,28.96,3.77,8.45,76.0,8.0,E
2,mario kart wii,Wii,2008,racing,15.68,12.76,3.79,3.29,82.0,8.3,E
3,wii sports resort,Wii,2009,sports,15.61,10.93,3.28,2.95,80.0,8.0,E
6,new super mario bros.,DS,2006,platform,11.28,9.14,6.50,2.88,89.0,8.5,E
7,wii play,Wii,2006,misc,13.96,9.18,2.93,2.84,58.0,6.6,E
...,...,...,...,...,...,...,...,...,...,...,...
16947,men in black ii: alien escape,GC,2003,shooter,0.01,0.00,0.00,0.00,-1.0,-1.0,T
16949,woody woodpecker in crazy castle 5,GBA,2002,platform,0.01,0.00,0.00,0.00,-1.0,-1.0,NaN
16950,score international baja 1000: the official game,PS2,2008,racing,0.00,0.00,0.00,0.00,-1.0,-1.0,NaN
16952,lma manager 2007,X360,2006,sports,0.00,0.01,0.00,0.00,-1.0,-1.0,NaN
16954,spirits & spells,GBA,2003,platform,0.01,0.00,0.00,0.00,-1.0,-1.0,NaN

In [63]:
# Подсчитаем сколько осталось строк в новом срезе
df_actual.shape[0]

12781

## Категоризация данных
    
Проведем категоризацию данных:
- Разделим все игры по оценкам пользователей и выделим такие категории: высокая оценка (от 8 до 10 включительно), средняя оценка (от 3 до 8, не включая правую границу интервала) и низкая оценка (от 0 до 3, не включая правую границу интервала).

In [79]:
# Используем функцию pd.cut()
df_actual['categorized_user_score'] = pd.cut(
    df_actual['user_score'], 
    bins=[0, 2, 7, 10], 
    labels=['низкая оценка', 'средняя оценка', 'высокая оценка']
)

Проверим, верно ли сработала категоризация

In [80]:
df_actual.loc[df_actual['categorized_user_score'] == 'низкая оценка']

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,categorized_user_score,categorized_critic_score
1057,deal or no deal,DS,2007,misc,1.15,0.40,0.00,0.15,20.0,1.9,E,низкая оценка,низкая оценка
1576,jillian michaels' fitness ultimatum 2009,Wii,2008,sports,0.96,0.20,0.00,0.11,30.0,2.0,E,низкая оценка,средняя оценка
2525,call of duty: modern warfare 3,Wii,2011,shooter,0.55,0.20,0.00,0.08,70.0,1.8,M,низкая оценка,средняя оценка
2978,fifa soccer 13,Wii,2012,action,0.18,0.44,0.00,0.07,-1.0,1.6,E,низкая оценка,NaN
4675,thrillville: off the rails,PS2,2007,strategy,0.20,0.16,0.00,0.05,70.0,1.7,E10+,низкая оценка,средняя оценка
4753,fifa 14,PSV,2013,sports,0.08,0.23,0.01,0.09,-1.0,1.8,E,низкая оценка,NaN
5337,amf bowling world lanes,Wii,2008,sports,0.33,0.00,0.00,0.03,-1.0,1.1,E,низкая оценка,NaN
5838,happy feet,DS,2006,action,0.27,0.01,0.00,0.02,-1.0,0.3,E,низкая оценка,NaN
5844,clash of the titans,PS3,2010,action,0.09,0.15,0.01,0.05,41.0,1.7,T,низкая оценка,средняя оценка
7394,angry birds star wars,PS4,2013,strategy,0.10,0.08,0.00,0.04,47.0,2.0,E,низкая оценка,средняя оценка
8309,mindjack,PS3,2011,shooter,0.07,0.07,0.00,0.03,44.0,1.7,M,низкая оценка,средняя оценка
8479,world destruction league: thunder tanks,PS,2000,action,0.09,0.06,0.00,0.01,35.0,1.2,T,низкая оценка,средняя оценка
9190,terminator 3: rise of the machines,XB,2003,action,0.11,0.03,0.00,0.01,35.0,2.0,T,низкая оценка,средняя оценка
9273,power gig: rise of the sixstring,PS3,2010,misc,0.13,0.00,0.00,0.01,36.0,0.5,T,низкая оценка,средняя оценка
9677,cabela's dangerous hunts 2009,PS3,2008,sports,0.12,0.00,0.00,0.01,39.0,1.8,T,низкая оценка,средняя оценка
9824,are you smarter than a 5th grader? game time,X360,2009,puzzle,0.12,0.00,0.00,0.01,-1.0,1.3,E,низкая оценка,NaN
9903,zathura,PS2,2005,adventure,0.06,0.05,0.00,0.02,43.0,2.0,E10+,низкая оценка,средняя оценка
10232,coraline,PS2,2009,action,0.06,0.04,0.00,0.01,39.0,2.0,E10+,низкая оценка,средняя оценка
10402,charlie and the chocolate factory,XB,2005,adventure,0.08,0.02,0.00,0.00,39.0,0.5,E,низкая оценка,средняя оценка
10622,thrillville: off the rails,PSP,2007,strategy,0.09,0.00,0.00,0.01,72.0,0.6,E10+,низкая оценка,средняя оценка
10798,rolling stone: drum king,Wii,2009,misc,0.09,0.00,0.00,0.01,32.0,1.8,T,низкая оценка,средняя оценка
10805,leisure suit larry: box office bust,PS3,2009,adventure,0.06,0.03,0.00,0.01,17.0,1.7,M,низкая оценка,низкая оценка
10848,big league sports,Wii,2008,sports,0.09,0.01,0.00,0.01,-1.0,1.4,E,низкая оценка,NaN
10872,dragon ball: evolution,PSP,2009,fighting,0.09,0.00,0.00,0.01,28.0,0.9,T,низкая оценка,низкая оценка
10988,mindjack,X360,2011,shooter,0.07,0.02,0.00,0.01,43.0,1.2,M,низкая оценка,средняя оценка
11033,family party: 30 great games,Wii,2008,misc,0.08,0.01,0.00,0.01,42.0,1.0,E10+,низкая оценка,средняя оценка
11338,the ant bully,Wii,2006,platform,0.08,0.00,0.00,0.01,45.0,1.4,E10+,низкая оценка,средняя оценка
11491,angry birds star wars,PSV,2013,strategy,0.03,0.03,0.00,0.02,-1.0,2.0,E,низкая оценка,NaN
11595,ninjabread man,Wii,2007,action,0.07,0.00,0.00,0.01,20.0,1.7,E,низкая оценка,низкая оценка
11905,medal of honor: underground,GBA,2002,shooter,0.05,0.02,0.00,0.00,46.0,1.7,T,низкая оценка,средняя оценка
12082,tom clancy's ghost recon 2,GC,2005,shooter,0.06,0.01,0.00,0.00,54.0,1.4,T,низкая оценка,средняя оценка
12473,bionicle,XB,2003,action,0.05,0.01,0.00,0.00,49.0,1.5,E,низкая оценка,средняя оценка
12569,johnny test,DS,2011,platform,0.06,0.00,0.00,0.00,-1.0,0.9,E,низкая оценка,NaN
12997,ride to hell,X360,2013,racing,0.04,0.01,0.00,0.01,19.0,1.3,M,низкая оценка,низкая оценка
13208,myth makers: orbs of doom,Wii,2007,puzzle,0.05,0.00,0.00,0.00,-1.0,1.1,E,низкая оценка,NaN
13562,billy the wizard: rocket broomstick racing,Wii,2007,racing,0.04,0.00,0.00,0.00,-1.0,0.3,E,низкая оценка,NaN
13608,pool party,Wii,2007,sports,0.04,0.00,0.00,0.00,32.0,0.7,E,низкая оценка,средняя оценка
13626,march of the penguins,DS,2006,adventure,0.04,0.00,0.00,0.00,34.0,1.7,E,низкая оценка,средняя оценка
13666,bad boys: miami takedown,GC,2004,shooter,0.03,0.01,0.00,0.00,35.0,2.0,M,низкая оценка,средняя оценка
13834,attack of the movies 3d,X360,2010,shooter,0.04,0.00,0.00,0.00,38.0,1.7,T,низкая оценка,средняя оценка
13870,myth makers: trixie in toyland,Wii,2008,platform,0.04,0.00,0.00,0.00,-1.0,0.2,E,низкая оценка,NaN
13877,ride to hell,PS3,2013,racing,0.02,0.01,0.00,0.01,13.0,1.0,M,низкая оценка,низкая оценка
15118,world war ii combat: road to berlin,XB,2006,shooter,0.02,0.01,0.00,0.00,-1.0,1.2,M,низкая оценка,NaN
15134,kawasaki snowmobiles,Wii,2008,racing,0.02,0.00,0.00,0.00,-1.0,2.0,E,низкая оценка,NaN
15431,kawasaki jet ski,Wii,2008,racing,0.02,0.00,0.00,0.00,-1.0,0.6,E,низкая оценка,NaN
16026,myth makers: super kart gp,Wii,2007,racing,0.01,0.00,0.00,0.00,-1.0,1.8,E,низкая оценка,NaN

In [81]:
df_actual.loc[df_actual['categorized_user_score'] == 'средняя оценка']

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,categorized_user_score,categorized_critic_score
7,wii play,Wii,2006,misc,13.96,9.18,2.93,2.84,58.0,6.6,E,средняя оценка,средняя оценка
14,kinect adventures!,X360,2010,misc,15.00,4.89,0.24,1.69,61.0,6.3,E,средняя оценка,средняя оценка
29,call of duty: modern warfare 3,X360,2011,shooter,9.04,4.24,0.13,1.32,88.0,3.4,M,средняя оценка,высокая оценка
32,call of duty: black ops,X360,2010,shooter,9.70,3.68,0.11,1.13,87.0,6.3,M,средняя оценка,высокая оценка
34,call of duty: black ops ii,PS3,2012,shooter,4.99,5.73,0.65,2.42,83.0,5.3,M,средняя оценка,высокая оценка
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16879,hospital tycoon,PC,2007,strategy,0.00,0.01,0.00,0.00,51.0,3.8,E10+,средняя оценка,средняя оценка
16893,ben 10 omniverse 2,X360,2013,action,0.00,0.01,0.00,0.00,-1.0,5.1,E10+,средняя оценка,NaN
16902,e.t. the extra-terrestrial,GBA,2001,action,0.01,0.00,0.00,0.00,46.0,2.4,E,средняя оценка,средняя оценка
16936,breach,PC,2011,shooter,0.01,0.00,0.00,0.00,61.0,5.8,T,средняя оценка,средняя оценка
16946,15 days,PC,2009,adventure,0.00,0.01,0.00,0.00,63.0,5.8,NaN,средняя оценка,средняя оценка

In [82]:
df_actual.loc[df_actual['categorized_user_score'] == 'высокая оценка']

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,categorized_user_score,categorized_critic_score
0,wii sports,Wii,2006,sports,41.36,28.96,3.77,8.45,76.0,8.0,E,высокая оценка,средняя оценка
2,mario kart wii,Wii,2008,racing,15.68,12.76,3.79,3.29,82.0,8.3,E,высокая оценка,высокая оценка
3,wii sports resort,Wii,2009,sports,15.61,10.93,3.28,2.95,80.0,8.0,E,высокая оценка,высокая оценка
6,new super mario bros.,DS,2006,platform,11.28,9.14,6.50,2.88,89.0,8.5,E,высокая оценка,высокая оценка
8,new super mario bros. wii,Wii,2009,platform,14.44,6.94,4.70,2.24,87.0,8.4,E,высокая оценка,высокая оценка
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16866,karnaaj rally,GBA,2003,racing,0.01,0.00,0.00,0.00,81.0,9.5,E,высокая оценка,высокая оценка
16875,deal or no deal,PC,2006,misc,0.00,0.01,0.00,0.00,-1.0,7.5,E,высокая оценка,NaN
16900,bookworm deluxe,PC,2006,puzzle,0.01,0.00,0.00,0.00,-1.0,8.0,E,высокая оценка,NaN
16913,mortal kombat: deadly alliance,GBA,2002,fighting,0.01,0.00,0.00,0.00,81.0,8.8,M,высокая оценка,высокая оценка
16943,storm: frontline nation,PC,2011,strategy,0.00,0.01,0.00,0.00,60.0,7.2,E10+,высокая оценка,средняя оценка

Категории назначены корректно

- Разделим все игры по оценкам критиков и выделим такие категории: высокая оценка (от 80 до 100 включительно), средняя оценка (от 30 до 80, не включая правую границу интервала) и низкая оценка (от 0 до 30, не включая правую границу интервала).

In [83]:
# Также используем функцию pd.cut()
df_actual['categorized_critic_score'] = pd.cut(
    df_actual['critic_score'], 
    bins=[0, 29, 79, 100], 
    labels=['низкая оценка', 'средняя оценка', 'высокая оценка']
)

Проверим насколько верно присвоены категории

In [84]:
df_actual.loc[df_actual['categorized_critic_score'] == 'низкая оценка']

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,categorized_user_score,categorized_critic_score
624,game party,Wii,2007,misc,1.47,0.77,0.0,0.24,25.0,4.3,E,средняя оценка,низкая оценка
921,game party 2,Wii,2008,misc,1.28,0.43,0.0,0.17,29.0,4.6,E,средняя оценка,низкая оценка
1057,deal or no deal,DS,2007,misc,1.15,0.40,0.0,0.15,20.0,1.9,E,низкая оценка,низкая оценка
5378,chicken shoot,Wii,2007,action,0.32,0.00,0.0,0.02,27.0,4.8,E10+,средняя оценка,низкая оценка
5610,deca sports freedom,X360,2010,sports,0.27,0.04,0.0,0.02,26.0,3.7,E10+,средняя оценка,низкая оценка
5821,kiss pinball,PS,2001,action,0.17,0.12,0.0,0.02,26.0,3.8,T,средняя оценка,низкая оценка
5882,calvin tucker's redneck jamboree,Wii,2008,misc,0.28,0.00,0.0,0.02,26.0,-1.0,E10+,NaN,низкая оценка
5901,shrek swamp kart speedway,GBA,2002,racing,0.22,0.08,0.0,0.01,27.0,8.9,E,высокая оценка,низкая оценка
7106,looney tunes: acme arsenal,Wii,2007,action,0.21,0.01,0.0,0.02,27.0,5.1,E10+,средняя оценка,низкая оценка
7315,nickelodeon party blast,XB,2002,misc,0.16,0.05,0.0,0.01,19.0,4.3,E,средняя оценка,низкая оценка
7444,hannah montana: the movie,X360,2009,adventure,0.14,0.05,0.0,0.02,25.0,3.8,E,средняя оценка,низкая оценка
7472,hbo boxing,PS,2000,fighting,0.12,0.08,0.0,0.01,26.0,4.0,E,средняя оценка,низкая оценка
7556,mortal kombat: special forces,PS,2000,fighting,0.12,0.08,0.0,0.01,28.0,2.4,M,средняя оценка,низкая оценка
7895,fighter within,XOne,2013,fighting,0.11,0.07,0.0,0.02,23.0,3.0,T,средняя оценка,низкая оценка
8602,leisure suit larry: box office bust,X360,2009,adventure,0.14,0.01,0.0,0.01,25.0,2.5,M,средняя оценка,низкая оценка
8903,bigfoot: collision course,DS,2009,racing,0.14,0.00,0.0,0.01,26.0,-1.0,E,NaN,низкая оценка
9231,chicken shoot,DS,2007,action,0.13,0.00,0.0,0.01,19.0,3.1,E10+,средняя оценка,низкая оценка
9464,rogue warrior,PS3,2009,shooter,0.11,0.01,0.0,0.01,27.0,2.8,M,средняя оценка,низкая оценка
9480,hulk hogan's main event,X360,2011,fighting,0.10,0.02,0.0,0.01,26.0,2.2,T,средняя оценка,низкая оценка
9520,peter jackson's king kong: the official game o...,DS,2005,action,0.12,0.00,0.0,0.01,28.0,3.2,T,средняя оценка,низкая оценка
9649,game party: champions,WiiU,2012,action,0.09,0.03,0.0,0.01,24.0,3.5,E,средняя оценка,низкая оценка
9945,godzilla unleashed: double smash,DS,2007,action,0.11,0.00,0.0,0.01,28.0,4.9,E,средняя оценка,низкая оценка
10060,cruis'n,Wii,2007,racing,0.10,0.01,0.0,0.01,25.0,3.7,E,средняя оценка,низкая оценка
10130,self-defense training camp,X360,2011,sports,0.08,0.03,0.0,0.01,21.0,5.0,T,средняя оценка,низкая оценка
10211,batman: dark tomorrow,XB,2003,action,0.08,0.02,0.0,0.00,25.0,3.6,T,средняя оценка,низкая оценка
10213,ping pals,DS,2004,misc,0.10,0.00,0.0,0.01,28.0,3.9,E,средняя оценка,низкая оценка
10274,pimp my ride,Wii,2008,racing,0.10,0.00,0.0,0.01,26.0,3.8,T,средняя оценка,низкая оценка
10311,truth or lies,X360,2010,misc,0.07,0.03,0.0,0.01,28.0,5.2,T,средняя оценка,низкая оценка
10499,rogue warrior,X360,2009,shooter,0.09,0.01,0.0,0.01,28.0,2.8,M,средняя оценка,низкая оценка
10561,gravity games bike: street vert dirt,PS2,2002,sports,0.05,0.04,0.0,0.01,24.0,4.1,T,средняя оценка,низкая оценка
10760,sudoku mania,DS,2006,puzzle,0.09,0.00,0.0,0.01,25.0,3.5,E,средняя оценка,низкая оценка
10805,leisure suit larry: box office bust,PS3,2009,adventure,0.06,0.03,0.0,0.01,17.0,1.7,M,низкая оценка,низкая оценка
10821,sneakers,XB,2002,puzzle,0.07,0.02,0.0,0.00,28.0,4.6,E,средняя оценка,низкая оценка
10872,dragon ball: evolution,PSP,2009,fighting,0.09,0.00,0.0,0.01,28.0,0.9,T,низкая оценка,низкая оценка
11359,jumper: griffin's story,Wii,2008,action,0.08,0.00,0.0,0.01,28.0,2.5,T,средняя оценка,низкая оценка
11595,ninjabread man,Wii,2007,action,0.07,0.00,0.0,0.01,20.0,1.7,E,низкая оценка,низкая оценка
11712,batman: dark tomorrow,GC,2003,action,0.06,0.02,0.0,0.00,29.0,3.2,T,средняя оценка,низкая оценка
11807,ultimate duck hunting,Wii,2009,sports,0.07,0.00,0.0,0.01,28.0,-1.0,T,NaN,низкая оценка
12001,godai: elemental force,PS2,2002,action,0.04,0.03,0.0,0.01,27.0,3.8,T,средняя оценка,низкая оценка
12131,homie rollerz,DS,2008,racing,0.07,0.00,0.0,0.01,23.0,2.4,E,средняя оценка,низкая оценка
12296,anubis ii,Wii,2007,platform,0.06,0.00,0.0,0.00,19.0,2.7,E,средняя оценка,низкая оценка
12344,legends of wrestling ii,GBA,2002,fighting,0.05,0.02,0.0,0.00,24.0,3.7,E,средняя оценка,низкая оценка
12621,biker mice from mars,PS2,2006,racing,0.03,0.02,0.0,0.01,27.0,-1.0,E10+,NaN,низкая оценка
12818,jumper: griffin's story,X360,2008,action,0.05,0.00,0.0,0.00,29.0,3.3,T,средняя оценка,низкая оценка
12900,animorphs: shattered reality,PS,2000,action,0.03,0.02,0.0,0.00,27.0,-1.0,E,NaN,низкая оценка
12997,ride to hell,X360,2013,racing,0.04,0.01,0.0,0.01,19.0,1.3,M,низкая оценка,низкая оценка
13296,jenga world tour,Wii,2007,misc,0.05,0.00,0.0,0.00,26.0,2.8,E,средняя оценка,низкая оценка
13877,ride to hell,PS3,2013,racing,0.02,0.01,0.0,0.01,13.0,1.0,M,низкая оценка,низкая оценка
14951,the island of dr. frankenstein,Wii,2009,adventure,0.03,0.00,0.0,0.00,26.0,-1.0,E,NaN,низкая оценка
15230,stake: fortune fighters,XB,2003,fighting,0.02,0.01,0.0,0.00,26.0,3.7,T,средняя оценка,низкая оценка
15562,balls of fury,Wii,2007,sports,0.02,0.00,0.0,0.00,19.0,2.8,E10+,средняя оценка,низкая оценка
15833,charlie's angels,GC,2003,action,0.01,0.00,0.0,0.00,23.0,3.3,T,средняя оценка,низкая оценка
15994,pulse racer,XB,2003,racing,0.01,0.00,0.0,0.00,24.0,2.8,E,средняя оценка,низкая оценка
16554,thunder alley,GBA,2004,racing,0.01,0.00,0.0,0.00,23.0,-1.0,E,NaN,низкая оценка
16589,aquaman: battle for atlantis,GC,2003,action,0.01,0.00,0.0,0.00,27.0,3.1,T,средняя оценка,низкая оценка

In [85]:
df_actual.loc[df_actual['categorized_critic_score'] == 'средняя оценка']

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,categorized_user_score,categorized_critic_score
0,wii sports,Wii,2006,sports,41.36,28.96,3.77,8.45,76.0,8.0,E,высокая оценка,средняя оценка
7,wii play,Wii,2006,misc,13.96,9.18,2.93,2.84,58.0,6.6,E,средняя оценка,средняя оценка
14,kinect adventures!,X360,2010,misc,15.00,4.89,0.24,1.69,61.0,6.3,E,средняя оценка,средняя оценка
19,brain age: train your brain in minutes a day,DS,2005,misc,4.74,9.20,4.16,2.04,77.0,7.9,E,высокая оценка,средняя оценка
26,brain age 2: more training in minutes a day,DS,2005,puzzle,3.43,5.35,5.32,1.18,77.0,7.1,E,высокая оценка,средняя оценка
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16936,breach,PC,2011,shooter,0.01,0.00,0.00,0.00,61.0,5.8,T,средняя оценка,средняя оценка
16937,bust-a-move 3000,GC,2003,puzzle,0.01,0.00,0.00,0.00,53.0,-1.0,E,NaN,средняя оценка
16938,mega brain boost,DS,2008,puzzle,0.01,0.00,0.00,0.00,48.0,-1.0,E,NaN,средняя оценка
16943,storm: frontline nation,PC,2011,strategy,0.00,0.01,0.00,0.00,60.0,7.2,E10+,высокая оценка,средняя оценка
16946,15 days,PC,2009,adventure,0.00,0.01,0.00,0.00,63.0,5.8,NaN,средняя оценка,средняя оценка

In [86]:
df_actual.loc[df_actual['categorized_critic_score'] == 'высокая оценка']

,name,platform,year_of_release,genre,na_sales,eu_sales,jp_sales,other_sales,critic_score,user_score,rating,categorized_user_score,categorized_critic_score
2,mario kart wii,Wii,2008,racing,15.68,12.76,3.79,3.29,82.0,8.3,E,высокая оценка,высокая оценка
3,wii sports resort,Wii,2009,sports,15.61,10.93,3.28,2.95,80.0,8.0,E,высокая оценка,высокая оценка
6,new super mario bros.,DS,2006,platform,11.28,9.14,6.50,2.88,89.0,8.5,E,высокая оценка,высокая оценка
8,new super mario bros. wii,Wii,2009,platform,14.44,6.94,4.70,2.24,87.0,8.4,E,высокая оценка,высокая оценка
11,mario kart ds,DS,2005,racing,9.71,7.47,4.13,1.90,91.0,8.6,E,высокая оценка,высокая оценка
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16789,winning eleven: pro evolution soccer 2007,PC,2006,sports,0.00,0.01,0.00,0.00,88.0,-1.0,E,NaN,высокая оценка
16811,king's bounty: armored princess,PC,2009,role-playing,0.00,0.01,0.00,0.00,82.0,8.6,T,высокая оценка,высокая оценка
16859,trine,PC,2009,action,0.00,0.01,0.00,0.00,80.0,8.2,E10+,высокая оценка,высокая оценка
16866,karnaaj rally,GBA,2003,racing,0.01,0.00,0.00,0.00,81.0,9.5,E,высокая оценка,высокая оценка
16913,mortal kombat: deadly alliance,GBA,2002,fighting,0.01,0.00,0.00,0.00,81.0,8.8,M,высокая оценка,высокая оценка

Все категории присвоены корректно

Сгруппируем данные по выделенным категориям и посчитаем количество игр в каждой категории.

In [87]:
# Применим метод groupby()
grouped_data_by_user_score = df_actual.groupby('categorized_user_score')['name'].count()

In [88]:
grouped_data_by_user_score

categorized_user_score
низкая оценка       46
средняя оценка    2351
высокая оценка    4085
Name: name, dtype: int64

In [89]:
grouped_data_by_critic_score = df_actual.groupby('categorized_critic_score')['name'].count()

In [75]:
grouped_data_by_critic_score

categorized_critic_score
низкая оценка       55
средняя оценка    5422
высокая оценка    1692
Name: name, dtype: int64

Выделим топ-7 платформ по количеству игр, выпущенных за весь актуальный период.

In [76]:
top_7_platforms = df_actual['platform'].value_counts().head(7)

In [77]:
top_7_platforms

platform
PS2     2127
DS      2120
Wii     1275
PSP     1180
X360    1121
PS3     1087
GBA      811
Name: count, dtype: int64

## Итоговый вывод

В ходе выполнения проекта была проведена полная предобработка исторических данных об игровой индустрии, после чего выполнен анализ в соответствии с поставленными задачами.



**1. Загрузка и первичный анализ данных:**
- Загружен датасет `new_games.csv`, содержащий 16 956 строк и 11 столбцов
- Выявлены некорректные типы данных в столбцах `year_of_release`, `eu_sales`, `jp_sales`, `user_score`

**2. Предобработка данных:**
- **Исправлены типы данных:** `eu_sales`, `jp_sales`, `user_score` приведены к float64, `year_of_release` — к int64
- **Обработаны пропуски:**
  - Удалены строки с пропусками в `year_of_release` (275 строк, 1.62%)
  - Заполнены индикатором `-1` пропуски в `user_score` (54.7%) и `critic_score` (51.5%)
 
- **Удалены дубликаты:** 235 явных дубликатов (1.39% от данных)
- **Нормализованы категориальные данные:**
  - `genre` приведён к нижнему регистру (устранены неявные дубликаты Action/ACTION и др.)
  - `rating` приведён к стандарту ESRB (замена устаревшего K-A на E)
  - `name` приведён к нижнему регистру
- **Общий объём удалённых данных:** 510 строк (3.01% от исходных)

**3. Фильтрация данных:**
- Отобран период с **2000 по 2013 год** включительно для анализа развития игровой индустрии в начале XXI века
- **Результат:** датафрейм `df_actual` содержит **12 781 строку** (сохранено 96.99% данных после всех этапов очистки)

**4. Категоризация данных:**
- **Добавлен новый столбец `categorized_user_score`** — категории оценок пользователей:
  - `высокая оценка` (8-10 баллов) — 4 085 игр
  - `средняя оценка` (3-8 баллов) — 2 351 игра
  - `низкая оценка` (0-3 балла) — 46 игр
  - *Игры без оценки (значение -1) автоматически получили NaN*
- **Добавлен новый столбец `categorized_critic_score`** — категории оценок критиков:
  - `высокая оценка` (80-100 баллов) — 1 692 игры
  - `средняя оценка` (30-80 баллов) — 5 422 игры
  - `низкая оценка` (0-30 баллов) — 55 игр
  - *Игры без оценки (значение -1) автоматически получили NaN*

**5. Выделение топ-7 платформ:**
- Определены платформы-лидеры по количеству выпущенных игр за период 2000-2013:
  1. **PS2** — 2 127 игр
  2. **DS** — 2 120 игр
  3. **Wii** — 1 275 игр
  4. **PSP** — 1 180 игр
  5. **X360** — 1 121 игра
  6. **PS3** — 1 087 игр
  7. **GBA** — 811 игр


**Ключевые результаты**

1. **Данные успешно очищены и подготовлены** к дальнейшему анализу. Потеря 3.01% исходных данных является незначительной и не влияет на репрезентативность выборки.

2. **Созданы новые категориальные поля** для удобства анализа связей между оценками и продажами игр.

3. **Определены платформы-лидеры** периода 2000-2013: PS2 и DS являются абсолютными лидерами по количеству выпущенных игр (более 2100 игр каждая).



**Заключение**

Все задачи, поставленные в проекте, выполнены. Данные приведены к корректному формату, очищены от пропусков и дубликатов, нормализованы, отфильтрованы по требуемому временному периоду, категоризированы по оценкам пользователей и критиков, выделены топ-7 платформ по количеству игр, создан датафрейм `df_actual` с новыми полями `categorized_user_score` и `categorized_critic_score`.